export * from './general'
export * from './shapeFlags'
export * from './normalizeProps'
export * from './toDisplayString'
export * from './patchFlags'
export * from './makeMap'
export * from './domTagConfig'